apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apinodedemo
  labels:
    app:  apinodedemo
spec:
  selector:
    matchLabels:
      app: apinodedemo
  replicas: 1
  template:
    metadata:
      labels:
        app:  apinodedemo
      annotations:
        repo: https://github.com/maxzavi/nodeapidemo
        swagger: n/a
    spec:
      containers:
      - name:  apinodedemo
        env:
          - name: DB_HOST
            value: HOST_K8S
          - name: DB_USERNAME
            value: myusername
          - name: DB_PORT
            value: "1500"
          - name: DB_PASSWORD
            value: "*******"
        image:  mzavaletav/apinodedemo:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  3000
          name:  port
      imagePullSecrets:
      - name: cr-mzavaletav
---
apiVersion: v1
kind: Service
metadata:
  name: apinodedemo-nodeport
spec:
  type: NodePort
  selector:
    app: apinodedemo
  ports:
    - port: 3000
      targetPort: 3000